server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://124.221.172.3:3306/lxfdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-pool-prepared-statement-per-connection-size: 20
      initial-size: 3
  devtools:
      restart:
        enabled: true  #热部署
  aop:
    proxy-target-class: true
  redis:
    host: 124.221.172.3
    port: 6379
    #password:
    jedis:
      pool:
        max-idle: 10  #连接池空闲最大
        min-idle: 2   #连接池空闲最小
        max-active: 200 #连接池最大链接数
        max-wait: 3000 #连接池最大超时时间