server:
  port: 8091
  servlet:
    context-path: /eas
spring:
  datasource:
    username: root
    password: lxf4994
    url: jdbc:mysql://124.221.172.3:3306/xyy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-pool-prepared-statement-per-connection-size: 20
      initial-size: 3
  devtools:
      restart:
        enabled: true  #热部署
  aop:
    proxy-target-class: true
  redis:
    host: 124.221.172.3
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 10  #连接池空闲最大
        min-idle: 2   #连接池空闲最小
        max-active: 200 #连接池最大链接数
        max-wait: 3000 #连接池最大超时时间
  rabbitmq:
    host: 124.221.172.3
    port: 5672
    username: lxf
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#swagger配置
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
#mybatis_plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

