server:
  port: 8091
  servlet:
    context-path: /eas
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true	# 开启sql日志输出
    # 配置数据源
    datasource:
      # 分库的逻辑库名,可配置多个
      names: demo0
      demo0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://124.221.172.3:3306/xyy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: lxf4994
    sharding:
      tables: # 逻辑表名
        t_order: # 逻辑表名
          actual-data-nodes: demo0.t_order$->{2022}$->{0}$->{5..7}
          table-strategy: # 分表策略
            standard:
              shardingColumn: create_time	# 分片路由标准
              #algorithm-expression: t_order$->{id % 2} # 分片算法表达式
              preciseAlgorithmClassName: com.lxf.eas.config.OrderPreciseAlgorithm
              rangeAlgorithmClassName: com.lxf.eas.config.OrderRangeAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
      binding-tables: t_order
      #default-database-strategy:	# 分库策略
        #inline:
          #sharding-column: id	# 分片路由标准
          #algorithm-expression: demo${id % 2}	# 分库策略表达式
  devtools:
      restart:
        enabled: true  #热部署
  aop:
    proxy-target-class: true
  redis:
    host: 124.221.172.3
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 10  #连接池空闲最大
        min-idle: 2   #连接池空闲最小
        max-active: 200 #连接池最大链接数
        max-wait: 3000 #连接池最大超时时间
  rabbitmq:
    host: 124.221.172.3
    port: 5672
    username: lxf
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#swagger配置
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
#mybatis_plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

